project:
  type: book
  output-dir: docs
  execute-dir: project

book:
  title: "Interpretable Gene Set Enrichment Analysis"
  author: "Karl Tayeb"
  date: "12/27/2024"
  chapters:
    - index.qmd
    - notebooks/gsea_simulated_example/index.qmd
    - part: "PBMC example"
      chapters:
        - notebooks/pbmcs/index.qmd
        - notebooks/pbmcs/table.qmd
    - part: "Plague analysis"
      chapters:
        - notebooks/plague_example/plague.qmd
    - notebooks/summary.qmd
    - notebooks/references.qmd

execute:
  freeze: true
  eval: false

bibliography: references.bib

format:
  html:
    theme: cosmo


